// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snap.proto

package com.uwei.easy_tsdb;

public final class SnapProto {
  private SnapProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SaveSnapRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:snap.SaveSnapRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * meta 库用 _meta
     * </pre>
     *
     * <code>repeated string databases = 1;</code>
     * @return A list containing the databases.
     */
    java.util.List<java.lang.String>
        getDatabasesList();
    /**
     * <pre>
     * meta 库用 _meta
     * </pre>
     *
     * <code>repeated string databases = 1;</code>
     * @return The count of databases.
     */
    int getDatabasesCount();
    /**
     * <pre>
     * meta 库用 _meta
     * </pre>
     *
     * <code>repeated string databases = 1;</code>
     * @param index The index of the element to return.
     * @return The databases at the given index.
     */
    java.lang.String getDatabases(int index);
    /**
     * <pre>
     * meta 库用 _meta
     * </pre>
     *
     * <code>repeated string databases = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the databases at the given index.
     */
    com.google.protobuf.ByteString
        getDatabasesBytes(int index);
  }
  /**
   * Protobuf type {@code snap.SaveSnapRequest}
   */
  public static final class SaveSnapRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:snap.SaveSnapRequest)
      SaveSnapRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SaveSnapRequest.newBuilder() to construct.
    private SaveSnapRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SaveSnapRequest() {
      databases_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SaveSnapRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SaveSnapRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                databases_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              databases_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          databases_ = databases_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.uwei.easy_tsdb.SnapProto.internal_static_snap_SaveSnapRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.uwei.easy_tsdb.SnapProto.internal_static_snap_SaveSnapRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.uwei.easy_tsdb.SnapProto.SaveSnapRequest.class, com.uwei.easy_tsdb.SnapProto.SaveSnapRequest.Builder.class);
    }

    public static final int DATABASES_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList databases_;
    /**
     * <pre>
     * meta 库用 _meta
     * </pre>
     *
     * <code>repeated string databases = 1;</code>
     * @return A list containing the databases.
     */
    public com.google.protobuf.ProtocolStringList
        getDatabasesList() {
      return databases_;
    }
    /**
     * <pre>
     * meta 库用 _meta
     * </pre>
     *
     * <code>repeated string databases = 1;</code>
     * @return The count of databases.
     */
    public int getDatabasesCount() {
      return databases_.size();
    }
    /**
     * <pre>
     * meta 库用 _meta
     * </pre>
     *
     * <code>repeated string databases = 1;</code>
     * @param index The index of the element to return.
     * @return The databases at the given index.
     */
    public java.lang.String getDatabases(int index) {
      return databases_.get(index);
    }
    /**
     * <pre>
     * meta 库用 _meta
     * </pre>
     *
     * <code>repeated string databases = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the databases at the given index.
     */
    public com.google.protobuf.ByteString
        getDatabasesBytes(int index) {
      return databases_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < databases_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, databases_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < databases_.size(); i++) {
          dataSize += computeStringSizeNoTag(databases_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getDatabasesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.uwei.easy_tsdb.SnapProto.SaveSnapRequest)) {
        return super.equals(obj);
      }
      com.uwei.easy_tsdb.SnapProto.SaveSnapRequest other = (com.uwei.easy_tsdb.SnapProto.SaveSnapRequest) obj;

      if (!getDatabasesList()
          .equals(other.getDatabasesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDatabasesCount() > 0) {
        hash = (37 * hash) + DATABASES_FIELD_NUMBER;
        hash = (53 * hash) + getDatabasesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.uwei.easy_tsdb.SnapProto.SaveSnapRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.uwei.easy_tsdb.SnapProto.SaveSnapRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.uwei.easy_tsdb.SnapProto.SaveSnapRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.uwei.easy_tsdb.SnapProto.SaveSnapRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.uwei.easy_tsdb.SnapProto.SaveSnapRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.uwei.easy_tsdb.SnapProto.SaveSnapRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.uwei.easy_tsdb.SnapProto.SaveSnapRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.uwei.easy_tsdb.SnapProto.SaveSnapRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.uwei.easy_tsdb.SnapProto.SaveSnapRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.uwei.easy_tsdb.SnapProto.SaveSnapRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.uwei.easy_tsdb.SnapProto.SaveSnapRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.uwei.easy_tsdb.SnapProto.SaveSnapRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.uwei.easy_tsdb.SnapProto.SaveSnapRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code snap.SaveSnapRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:snap.SaveSnapRequest)
        com.uwei.easy_tsdb.SnapProto.SaveSnapRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.uwei.easy_tsdb.SnapProto.internal_static_snap_SaveSnapRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.uwei.easy_tsdb.SnapProto.internal_static_snap_SaveSnapRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.uwei.easy_tsdb.SnapProto.SaveSnapRequest.class, com.uwei.easy_tsdb.SnapProto.SaveSnapRequest.Builder.class);
      }

      // Construct using com.uwei.easy_tsdb.SnapProto.SaveSnapRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        databases_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.uwei.easy_tsdb.SnapProto.internal_static_snap_SaveSnapRequest_descriptor;
      }

      @java.lang.Override
      public com.uwei.easy_tsdb.SnapProto.SaveSnapRequest getDefaultInstanceForType() {
        return com.uwei.easy_tsdb.SnapProto.SaveSnapRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.uwei.easy_tsdb.SnapProto.SaveSnapRequest build() {
        com.uwei.easy_tsdb.SnapProto.SaveSnapRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.uwei.easy_tsdb.SnapProto.SaveSnapRequest buildPartial() {
        com.uwei.easy_tsdb.SnapProto.SaveSnapRequest result = new com.uwei.easy_tsdb.SnapProto.SaveSnapRequest(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          databases_ = databases_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.databases_ = databases_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.uwei.easy_tsdb.SnapProto.SaveSnapRequest) {
          return mergeFrom((com.uwei.easy_tsdb.SnapProto.SaveSnapRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.uwei.easy_tsdb.SnapProto.SaveSnapRequest other) {
        if (other == com.uwei.easy_tsdb.SnapProto.SaveSnapRequest.getDefaultInstance()) return this;
        if (!other.databases_.isEmpty()) {
          if (databases_.isEmpty()) {
            databases_ = other.databases_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDatabasesIsMutable();
            databases_.addAll(other.databases_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.uwei.easy_tsdb.SnapProto.SaveSnapRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.uwei.easy_tsdb.SnapProto.SaveSnapRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList databases_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDatabasesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          databases_ = new com.google.protobuf.LazyStringArrayList(databases_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * meta 库用 _meta
       * </pre>
       *
       * <code>repeated string databases = 1;</code>
       * @return A list containing the databases.
       */
      public com.google.protobuf.ProtocolStringList
          getDatabasesList() {
        return databases_.getUnmodifiableView();
      }
      /**
       * <pre>
       * meta 库用 _meta
       * </pre>
       *
       * <code>repeated string databases = 1;</code>
       * @return The count of databases.
       */
      public int getDatabasesCount() {
        return databases_.size();
      }
      /**
       * <pre>
       * meta 库用 _meta
       * </pre>
       *
       * <code>repeated string databases = 1;</code>
       * @param index The index of the element to return.
       * @return The databases at the given index.
       */
      public java.lang.String getDatabases(int index) {
        return databases_.get(index);
      }
      /**
       * <pre>
       * meta 库用 _meta
       * </pre>
       *
       * <code>repeated string databases = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the databases at the given index.
       */
      public com.google.protobuf.ByteString
          getDatabasesBytes(int index) {
        return databases_.getByteString(index);
      }
      /**
       * <pre>
       * meta 库用 _meta
       * </pre>
       *
       * <code>repeated string databases = 1;</code>
       * @param index The index to set the value at.
       * @param value The databases to set.
       * @return This builder for chaining.
       */
      public Builder setDatabases(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDatabasesIsMutable();
        databases_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * meta 库用 _meta
       * </pre>
       *
       * <code>repeated string databases = 1;</code>
       * @param value The databases to add.
       * @return This builder for chaining.
       */
      public Builder addDatabases(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDatabasesIsMutable();
        databases_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * meta 库用 _meta
       * </pre>
       *
       * <code>repeated string databases = 1;</code>
       * @param values The databases to add.
       * @return This builder for chaining.
       */
      public Builder addAllDatabases(
          java.lang.Iterable<java.lang.String> values) {
        ensureDatabasesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, databases_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * meta 库用 _meta
       * </pre>
       *
       * <code>repeated string databases = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDatabases() {
        databases_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * meta 库用 _meta
       * </pre>
       *
       * <code>repeated string databases = 1;</code>
       * @param value The bytes of the databases to add.
       * @return This builder for chaining.
       */
      public Builder addDatabasesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureDatabasesIsMutable();
        databases_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:snap.SaveSnapRequest)
    }

    // @@protoc_insertion_point(class_scope:snap.SaveSnapRequest)
    private static final com.uwei.easy_tsdb.SnapProto.SaveSnapRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.uwei.easy_tsdb.SnapProto.SaveSnapRequest();
    }

    public static com.uwei.easy_tsdb.SnapProto.SaveSnapRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SaveSnapRequest>
        PARSER = new com.google.protobuf.AbstractParser<SaveSnapRequest>() {
      @java.lang.Override
      public SaveSnapRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SaveSnapRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SaveSnapRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SaveSnapRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.uwei.easy_tsdb.SnapProto.SaveSnapRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SaveSnapResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:snap.SaveSnapResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code snap.SaveSnapResponse}
   */
  public static final class SaveSnapResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:snap.SaveSnapResponse)
      SaveSnapResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SaveSnapResponse.newBuilder() to construct.
    private SaveSnapResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SaveSnapResponse() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SaveSnapResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SaveSnapResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.uwei.easy_tsdb.SnapProto.internal_static_snap_SaveSnapResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.uwei.easy_tsdb.SnapProto.internal_static_snap_SaveSnapResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.uwei.easy_tsdb.SnapProto.SaveSnapResponse.class, com.uwei.easy_tsdb.SnapProto.SaveSnapResponse.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.uwei.easy_tsdb.SnapProto.SaveSnapResponse)) {
        return super.equals(obj);
      }
      com.uwei.easy_tsdb.SnapProto.SaveSnapResponse other = (com.uwei.easy_tsdb.SnapProto.SaveSnapResponse) obj;

      if (getCode()
          != other.getCode()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.uwei.easy_tsdb.SnapProto.SaveSnapResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.uwei.easy_tsdb.SnapProto.SaveSnapResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.uwei.easy_tsdb.SnapProto.SaveSnapResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.uwei.easy_tsdb.SnapProto.SaveSnapResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.uwei.easy_tsdb.SnapProto.SaveSnapResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.uwei.easy_tsdb.SnapProto.SaveSnapResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.uwei.easy_tsdb.SnapProto.SaveSnapResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.uwei.easy_tsdb.SnapProto.SaveSnapResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.uwei.easy_tsdb.SnapProto.SaveSnapResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.uwei.easy_tsdb.SnapProto.SaveSnapResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.uwei.easy_tsdb.SnapProto.SaveSnapResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.uwei.easy_tsdb.SnapProto.SaveSnapResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.uwei.easy_tsdb.SnapProto.SaveSnapResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code snap.SaveSnapResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:snap.SaveSnapResponse)
        com.uwei.easy_tsdb.SnapProto.SaveSnapResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.uwei.easy_tsdb.SnapProto.internal_static_snap_SaveSnapResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.uwei.easy_tsdb.SnapProto.internal_static_snap_SaveSnapResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.uwei.easy_tsdb.SnapProto.SaveSnapResponse.class, com.uwei.easy_tsdb.SnapProto.SaveSnapResponse.Builder.class);
      }

      // Construct using com.uwei.easy_tsdb.SnapProto.SaveSnapResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.uwei.easy_tsdb.SnapProto.internal_static_snap_SaveSnapResponse_descriptor;
      }

      @java.lang.Override
      public com.uwei.easy_tsdb.SnapProto.SaveSnapResponse getDefaultInstanceForType() {
        return com.uwei.easy_tsdb.SnapProto.SaveSnapResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.uwei.easy_tsdb.SnapProto.SaveSnapResponse build() {
        com.uwei.easy_tsdb.SnapProto.SaveSnapResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.uwei.easy_tsdb.SnapProto.SaveSnapResponse buildPartial() {
        com.uwei.easy_tsdb.SnapProto.SaveSnapResponse result = new com.uwei.easy_tsdb.SnapProto.SaveSnapResponse(this);
        result.code_ = code_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.uwei.easy_tsdb.SnapProto.SaveSnapResponse) {
          return mergeFrom((com.uwei.easy_tsdb.SnapProto.SaveSnapResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.uwei.easy_tsdb.SnapProto.SaveSnapResponse other) {
        if (other == com.uwei.easy_tsdb.SnapProto.SaveSnapResponse.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.uwei.easy_tsdb.SnapProto.SaveSnapResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.uwei.easy_tsdb.SnapProto.SaveSnapResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ ;
      /**
       * <code>int32 code = 1;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:snap.SaveSnapResponse)
    }

    // @@protoc_insertion_point(class_scope:snap.SaveSnapResponse)
    private static final com.uwei.easy_tsdb.SnapProto.SaveSnapResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.uwei.easy_tsdb.SnapProto.SaveSnapResponse();
    }

    public static com.uwei.easy_tsdb.SnapProto.SaveSnapResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SaveSnapResponse>
        PARSER = new com.google.protobuf.AbstractParser<SaveSnapResponse>() {
      @java.lang.Override
      public SaveSnapResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SaveSnapResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SaveSnapResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SaveSnapResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.uwei.easy_tsdb.SnapProto.SaveSnapResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snap_SaveSnapRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snap_SaveSnapRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_snap_SaveSnapResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_snap_SaveSnapResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nsnap.proto\022\004snap\"$\n\017SaveSnapRequest\022\021\n" +
      "\tdatabases\030\001 \003(\t\"1\n\020SaveSnapResponse\022\014\n\004" +
      "code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t2?\n\004snap\0227\n\004s" +
      "ave\022\025.snap.SaveSnapRequest\032\026.snap.SaveSn" +
      "apResponse\"\000B\037\n\022com.uwei.easy_tsdbB\tSnap" +
      "Protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_snap_SaveSnapRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_snap_SaveSnapRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snap_SaveSnapRequest_descriptor,
        new java.lang.String[] { "Databases", });
    internal_static_snap_SaveSnapResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_snap_SaveSnapResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_snap_SaveSnapResponse_descriptor,
        new java.lang.String[] { "Code", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
