// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gremlin.proto

package com.uwei.easy_core;

public final class GremlinProto {
  private GremlinProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GremlinRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gremlin.GremlinRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string database = 1;</code>
     * @return The database.
     */
    java.lang.String getDatabase();
    /**
     * <code>string database = 1;</code>
     * @return The bytes for database.
     */
    com.google.protobuf.ByteString
        getDatabaseBytes();

    /**
     * <code>string statement = 2;</code>
     * @return The statement.
     */
    java.lang.String getStatement();
    /**
     * <code>string statement = 2;</code>
     * @return The bytes for statement.
     */
    com.google.protobuf.ByteString
        getStatementBytes();
  }
  /**
   * Protobuf type {@code gremlin.GremlinRequest}
   */
  public static final class GremlinRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gremlin.GremlinRequest)
      GremlinRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GremlinRequest.newBuilder() to construct.
    private GremlinRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GremlinRequest() {
      database_ = "";
      statement_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GremlinRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GremlinRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              database_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              statement_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.uwei.easy_core.GremlinProto.internal_static_gremlin_GremlinRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.uwei.easy_core.GremlinProto.internal_static_gremlin_GremlinRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.uwei.easy_core.GremlinProto.GremlinRequest.class, com.uwei.easy_core.GremlinProto.GremlinRequest.Builder.class);
    }

    public static final int DATABASE_FIELD_NUMBER = 1;
    private volatile java.lang.Object database_;
    /**
     * <code>string database = 1;</code>
     * @return The database.
     */
    @java.lang.Override
    public java.lang.String getDatabase() {
      java.lang.Object ref = database_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        database_ = s;
        return s;
      }
    }
    /**
     * <code>string database = 1;</code>
     * @return The bytes for database.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDatabaseBytes() {
      java.lang.Object ref = database_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        database_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATEMENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object statement_;
    /**
     * <code>string statement = 2;</code>
     * @return The statement.
     */
    @java.lang.Override
    public java.lang.String getStatement() {
      java.lang.Object ref = statement_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        statement_ = s;
        return s;
      }
    }
    /**
     * <code>string statement = 2;</code>
     * @return The bytes for statement.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStatementBytes() {
      java.lang.Object ref = statement_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        statement_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDatabaseBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, database_);
      }
      if (!getStatementBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, statement_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDatabaseBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, database_);
      }
      if (!getStatementBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, statement_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.uwei.easy_core.GremlinProto.GremlinRequest)) {
        return super.equals(obj);
      }
      com.uwei.easy_core.GremlinProto.GremlinRequest other = (com.uwei.easy_core.GremlinProto.GremlinRequest) obj;

      if (!getDatabase()
          .equals(other.getDatabase())) return false;
      if (!getStatement()
          .equals(other.getStatement())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATABASE_FIELD_NUMBER;
      hash = (53 * hash) + getDatabase().hashCode();
      hash = (37 * hash) + STATEMENT_FIELD_NUMBER;
      hash = (53 * hash) + getStatement().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.uwei.easy_core.GremlinProto.GremlinRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.uwei.easy_core.GremlinProto.GremlinRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.uwei.easy_core.GremlinProto.GremlinRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.uwei.easy_core.GremlinProto.GremlinRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.uwei.easy_core.GremlinProto.GremlinRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.uwei.easy_core.GremlinProto.GremlinRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.uwei.easy_core.GremlinProto.GremlinRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.uwei.easy_core.GremlinProto.GremlinRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.uwei.easy_core.GremlinProto.GremlinRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.uwei.easy_core.GremlinProto.GremlinRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.uwei.easy_core.GremlinProto.GremlinRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.uwei.easy_core.GremlinProto.GremlinRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.uwei.easy_core.GremlinProto.GremlinRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gremlin.GremlinRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gremlin.GremlinRequest)
        com.uwei.easy_core.GremlinProto.GremlinRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.uwei.easy_core.GremlinProto.internal_static_gremlin_GremlinRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.uwei.easy_core.GremlinProto.internal_static_gremlin_GremlinRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.uwei.easy_core.GremlinProto.GremlinRequest.class, com.uwei.easy_core.GremlinProto.GremlinRequest.Builder.class);
      }

      // Construct using com.uwei.easy_core.GremlinProto.GremlinRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        database_ = "";

        statement_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.uwei.easy_core.GremlinProto.internal_static_gremlin_GremlinRequest_descriptor;
      }

      @java.lang.Override
      public com.uwei.easy_core.GremlinProto.GremlinRequest getDefaultInstanceForType() {
        return com.uwei.easy_core.GremlinProto.GremlinRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.uwei.easy_core.GremlinProto.GremlinRequest build() {
        com.uwei.easy_core.GremlinProto.GremlinRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.uwei.easy_core.GremlinProto.GremlinRequest buildPartial() {
        com.uwei.easy_core.GremlinProto.GremlinRequest result = new com.uwei.easy_core.GremlinProto.GremlinRequest(this);
        result.database_ = database_;
        result.statement_ = statement_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.uwei.easy_core.GremlinProto.GremlinRequest) {
          return mergeFrom((com.uwei.easy_core.GremlinProto.GremlinRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.uwei.easy_core.GremlinProto.GremlinRequest other) {
        if (other == com.uwei.easy_core.GremlinProto.GremlinRequest.getDefaultInstance()) return this;
        if (!other.getDatabase().isEmpty()) {
          database_ = other.database_;
          onChanged();
        }
        if (!other.getStatement().isEmpty()) {
          statement_ = other.statement_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.uwei.easy_core.GremlinProto.GremlinRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.uwei.easy_core.GremlinProto.GremlinRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object database_ = "";
      /**
       * <code>string database = 1;</code>
       * @return The database.
       */
      public java.lang.String getDatabase() {
        java.lang.Object ref = database_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          database_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string database = 1;</code>
       * @return The bytes for database.
       */
      public com.google.protobuf.ByteString
          getDatabaseBytes() {
        java.lang.Object ref = database_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          database_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string database = 1;</code>
       * @param value The database to set.
       * @return This builder for chaining.
       */
      public Builder setDatabase(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        database_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string database = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDatabase() {
        
        database_ = getDefaultInstance().getDatabase();
        onChanged();
        return this;
      }
      /**
       * <code>string database = 1;</code>
       * @param value The bytes for database to set.
       * @return This builder for chaining.
       */
      public Builder setDatabaseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        database_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object statement_ = "";
      /**
       * <code>string statement = 2;</code>
       * @return The statement.
       */
      public java.lang.String getStatement() {
        java.lang.Object ref = statement_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          statement_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string statement = 2;</code>
       * @return The bytes for statement.
       */
      public com.google.protobuf.ByteString
          getStatementBytes() {
        java.lang.Object ref = statement_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          statement_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string statement = 2;</code>
       * @param value The statement to set.
       * @return This builder for chaining.
       */
      public Builder setStatement(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        statement_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string statement = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatement() {
        
        statement_ = getDefaultInstance().getStatement();
        onChanged();
        return this;
      }
      /**
       * <code>string statement = 2;</code>
       * @param value The bytes for statement to set.
       * @return This builder for chaining.
       */
      public Builder setStatementBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        statement_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gremlin.GremlinRequest)
    }

    // @@protoc_insertion_point(class_scope:gremlin.GremlinRequest)
    private static final com.uwei.easy_core.GremlinProto.GremlinRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.uwei.easy_core.GremlinProto.GremlinRequest();
    }

    public static com.uwei.easy_core.GremlinProto.GremlinRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GremlinRequest>
        PARSER = new com.google.protobuf.AbstractParser<GremlinRequest>() {
      @java.lang.Override
      public GremlinRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GremlinRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GremlinRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GremlinRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.uwei.easy_core.GremlinProto.GremlinRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gremlin_GremlinRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gremlin_GremlinRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rgremlin.proto\022\007gremlin\032\016instance.proto" +
      "\"5\n\016GremlinRequest\022\020\n\010database\030\001 \001(\t\022\021\n\t" +
      "statement\030\002 \001(\t2@\n\007gremlin\0225\n\004exec\022\027.gre" +
      "mlin.GremlinRequest\032\022.instance.Response\"" +
      "\000B\"\n\022com.uwei.easy_coreB\014GremlinProtob\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.uwei.easy_core.InstanceProto.getDescriptor(),
        });
    internal_static_gremlin_GremlinRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gremlin_GremlinRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gremlin_GremlinRequest_descriptor,
        new java.lang.String[] { "Database", "Statement", });
    com.uwei.easy_core.InstanceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
